<?php

/**
 * @file
 * Font list for the Edge Fonts module.
 */

/**
 * Helper function - hardcodes the list of available fonts and their variants.
 *
 * Updated 16-Oct-2012.
 */
function edge_fonts_list() {
  return array(
    'abel' => array(
      'fontname' => 'Abel',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'abril-fatface' => array(
      'fontname' => 'Abril Fatface',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'aclonica' => array(
      'fontname' => 'Aclonica',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'acme' => array(
      'fontname' => 'Acme',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'actor' => array(
      'fontname' => 'Actor',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'adamina' => array(
      'fontname' => 'Adamina',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'advent-pro' => array(
      'fontname' => 'Advent Pro',
      'variants' => array(
        'n1' => 'Thin',
        'n2' => 'Extra Light',
        'n3' => 'Light',
        'n4' => 'Regular',
        'n5' => 'Medium',
        'n6' => 'Semibold',
        'n7' => 'Bold',
      ),
    ),
    'aguafina-script' => array(
      'fontname' => 'Aguafina Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'aladin' => array(
      'fontname' => 'Aladin',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'alegreya' => array(
      'fontname' => 'Alegreya',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
        'n9' => 'Black',
        'i9' => 'Black Italic',
      ),
    ),
    'alegreya-sc' => array(
      'fontname' => 'Alegreya SC',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'BoldItalic',
        'n9' => 'Black',
        'i9' => 'BlackItalic',
      ),
    ),
    'alex-brush' => array(
      'fontname' => 'Alex Brush',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'alexa-std' => array(
      'fontname' => 'Alexa Std',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'alfa-slab-one' => array(
      'fontname' => 'Alfa Slab One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'alice' => array(
      'fontname' => 'Alice',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'alike' => array(
      'fontname' => 'Alike',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'alike-angular' => array(
      'fontname' => 'Alike Angular',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'allan' => array(
      'fontname' => 'Allan',
      'variants' => array(
        'n7' => 'Bold',
      ),
    ),
    'allerta' => array(
      'fontname' => 'Allerta',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'allura' => array(
      'fontname' => 'Allura',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'almendra' => array(
      'fontname' => 'Almendra',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'almendra-sc' => array(
      'fontname' => 'Almendra SC',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'amaranth' => array(
      'fontname' => 'Amaranth',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'amatic-sc' => array(
      'fontname' => 'Amatic SC',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'amethysta' => array(
      'fontname' => 'Amethysta',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'andada' => array(
      'fontname' => 'Andada',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'andika' => array(
      'fontname' => 'Andika',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'annie-use-your-telescope' => array(
      'fontname' => 'Annie Use Your Telescope',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'anonymous-pro' => array(
      'fontname' => 'Anonymous Pro',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'antic' => array(
      'fontname' => 'Antic',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'antic-didone' => array(
      'fontname' => 'Antic Didone',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'antic-slab' => array(
      'fontname' => 'Antic Slab',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'arapey' => array(
      'fontname' => 'Arapey',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'arbutus' => array(
      'fontname' => 'Arbutus',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'architects-daughter' => array(
      'fontname' => 'Architects Daughter',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'arimo' => array(
      'fontname' => 'Arimo',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'arizonia' => array(
      'fontname' => 'Arizonia',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'artifika' => array(
      'fontname' => 'Artifika',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'arvo' => array(
      'fontname' => 'Arvo',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'asap' => array(
      'fontname' => 'Asap',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'asset' => array(
      'fontname' => 'Asset',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'astloch' => array(
      'fontname' => 'Astloch',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'asul' => array(
      'fontname' => 'Asul',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'atomic-age' => array(
      'fontname' => 'Atomic Age',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'aubrey' => array(
      'fontname' => 'Aubrey',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'average' => array(
      'fontname' => 'Average',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'averia-gruesa-libre' => array(
      'fontname' => 'Averia Gruesa Libre',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'averia-libre' => array(
      'fontname' => 'Averia Libre',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'averia-sans-libre' => array(
      'fontname' => 'Averia Sans Libre',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'averia-serif-libre' => array(
      'fontname' => 'Averia Serif Libre',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'bad-script' => array(
      'fontname' => 'Bad Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'balthazar' => array(
      'fontname' => 'Balthazar',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bangers' => array(
      'fontname' => 'Bangers',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'basic' => array(
      'fontname' => 'Basic',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'baumans' => array(
      'fontname' => 'Baumans',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bebas-neue' => array(
      'fontname' => 'Bebas Neue',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'belgrano' => array(
      'fontname' => 'Belgrano',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bentham' => array(
      'fontname' => 'Bentham',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'berkshire-swash' => array(
      'fontname' => 'Berkshire Swash',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bigshot-one' => array(
      'fontname' => 'Bigshot One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bilbo' => array(
      'fontname' => 'Bilbo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bilbo-swash-caps' => array(
      'fontname' => 'Bilbo Swash Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bitter' => array(
      'fontname' => 'Bitter',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'black-ops-one' => array(
      'fontname' => 'Black Ops One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bonbon' => array(
      'fontname' => 'Bonbon',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'boogaloo' => array(
      'fontname' => 'Boogaloo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bowlby-one' => array(
      'fontname' => 'Bowlby One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bowlby-one-sc' => array(
      'fontname' => 'Bowlby One SC',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'brawler' => array(
      'fontname' => 'Brawler',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bree-serif' => array(
      'fontname' => 'Bree Serif',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'brush-script-std' => array(
      'fontname' => 'Brush Script Std',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bubblegum-sans' => array(
      'fontname' => 'Bubblegum Sans',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'bubbler-one' => array(
      'fontname' => 'Bubbler One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'buda' => array(
      'fontname' => 'Buda',
      'variants' => array(
        'n3' => 'Light',
      ),
    ),
    'buenard' => array(
      'fontname' => 'Buenard',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'butcherman' => array(
      'fontname' => 'Butcherman',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'butcherman-caps' => array(
      'fontname' => 'Butcherman Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'butterfly-kids' => array(
      'fontname' => 'Butterfly Kids',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cabin' => array(
      'fontname' => 'Cabin',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n5' => 'Medium',
        'i5' => 'Medium Italic',
        'n6' => 'Semibold',
        'i6' => 'Semibold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'cabin-condensed' => array(
      'fontname' => 'Cabin Condensed',
      'variants' => array(
        'n4' => 'Regular',
        'n5' => 'Medium',
        'n6' => 'Semibold',
        'n7' => 'Bold',
      ),
    ),
    'cabin-sketch' => array(
      'fontname' => 'Cabin Sketch',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'caesar-dressing' => array(
      'fontname' => 'Caesar Dressing',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cagliostro' => array(
      'fontname' => 'Cagliostro',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'calligraffitti' => array(
      'fontname' => 'Calligraffitti',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cambo' => array(
      'fontname' => 'Cambo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cantarell' => array(
      'fontname' => 'Cantarell',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Oblique',
        'n7' => 'Bold',
        'i7' => 'Bold Oblique',
      ),
    ),
    'cantata-one' => array(
      'fontname' => 'Cantata One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cardo' => array(
      'fontname' => 'Cardo',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'carme' => array(
      'fontname' => 'Carme',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'carter-one' => array(
      'fontname' => 'Carter One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'caudex' => array(
      'fontname' => 'Caudex',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'cedarville-cursive' => array(
      'fontname' => 'Cedarville Cursive',
      'variants' => array(
        'n4' => 'Cursive',
      ),
    ),
    'ceviche-one' => array(
      'fontname' => 'Ceviche One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'changa-one' => array(
      'fontname' => 'Changa One',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'chango' => array(
      'fontname' => 'Chango',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'chelsea-market' => array(
      'fontname' => 'Chelsea Market',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cherry-cream-soda' => array(
      'fontname' => 'Cherry Cream Soda',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'chewy' => array(
      'fontname' => 'Chewy',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'chicle' => array(
      'fontname' => 'Chicle',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'chivo' => array(
      'fontname' => 'Chivo',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n9' => 'Black',
        'i9' => 'Black Italic',
      ),
    ),
    'chunk' => array(
      'fontname' => 'Chunk',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'clara' => array(
      'fontname' => 'Clara',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'coda' => array(
      'fontname' => 'Coda',
      'variants' => array(
        'n4' => 'Regular',
        'n8' => 'Heavy',
      ),
    ),
    'coda-caption' => array(
      'fontname' => 'Coda Caption',
      'variants' => array(
        'n8' => 'Heavy',
      ),
    ),
    'codystar' => array(
      'fontname' => 'Codystar',
      'variants' => array(
        'n3' => 'Light',
        'n4' => 'Regular',
      ),
    ),
    'comfortaa' => array(
      'fontname' => 'Comfortaa',
      'variants' => array(
        'n3' => 'Light',
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'coming-soon' => array(
      'fontname' => 'Coming Soon',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'concert-one' => array(
      'fontname' => 'Concert One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'condiment' => array(
      'fontname' => 'Condiment',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'contrail-one' => array(
      'fontname' => 'Contrail One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'convergence' => array(
      'fontname' => 'Convergence',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cookie' => array(
      'fontname' => 'Cookie',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cooper-black-std' => array(
      'fontname' => 'Cooper Black Std',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'copse' => array(
      'fontname' => 'Copse',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'corben' => array(
      'fontname' => 'Corben',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'cousine' => array(
      'fontname' => 'Cousine',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'coustard' => array(
      'fontname' => 'Coustard',
      'variants' => array(
        'n4' => 'Regular',
        'n9' => 'Black',
      ),
    ),
    'covered-by-your-grace' => array(
      'fontname' => 'Covered By Your Grace',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'crafty-girls' => array(
      'fontname' => 'Crafty Girls',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'creepster' => array(
      'fontname' => 'Creepster',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'creepster-caps' => array(
      'fontname' => 'Creepster Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'crete-round' => array(
      'fontname' => 'Crete Round',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'crimson-text' => array(
      'fontname' => 'Crimson Text',
      'variants' => array(
        'n4' => 'Roman',
        'i4' => 'Italic',
        'n6' => 'Semibold',
        'i6' => 'Semibold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'crushed' => array(
      'fontname' => 'Crushed',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cuprum' => array(
      'fontname' => 'Cuprum',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'cutive' => array(
      'fontname' => 'Cutive',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'damion' => array(
      'fontname' => 'Damion',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'dancing-script' => array(
      'fontname' => 'Dancing Script',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'dawning-of-a-new-day' => array(
      'fontname' => 'Dawning of a New Day',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'days-one' => array(
      'fontname' => 'Days One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'de-walpergens-pica' => array(
      'fontname' => 'De Walpergen\'s Pica',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'de-walpergens-pica-small-caps' => array(
      'fontname' => 'De Walpergen\'s Pica Small Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'delius' => array(
      'fontname' => 'Delius',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'delius-swash-caps' => array(
      'fontname' => 'Delius Swash Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'delius-unicase' => array(
      'fontname' => 'Delius Unicase',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'devonshire' => array(
      'fontname' => 'Devonshire',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'dhyana' => array(
      'fontname' => 'Dhyana',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'didact-gothic' => array(
      'fontname' => 'Didact Gothic',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'diplomata' => array(
      'fontname' => 'Diplomata',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'diplomata-sc' => array(
      'fontname' => 'Diplomata SC',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'doppio-one' => array(
      'fontname' => 'Doppio One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'dorsa' => array(
      'fontname' => 'Dorsa',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'dosis' => array(
      'fontname' => 'Dosis',
      'variants' => array(
        'n2' => 'Extra Light',
        'n3' => 'Light',
        'n4' => 'Regular',
        'n5' => 'Medium',
        'n6' => 'Semibold',
        'n7' => 'Bold',
        'n8' => 'Extra Bold',
      ),
    ),
    'double-pica' => array(
      'fontname' => 'Double Pica',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'double-pica-small-caps' => array(
      'fontname' => 'Double Pica Small Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'dr-sugiyama' => array(
      'fontname' => 'Dr Sugiyama',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'droid-sans' => array(
      'fontname' => 'Droid Sans',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'droid-sans-mono' => array(
      'fontname' => 'Droid Sans Mono',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'droid-serif' => array(
      'fontname' => 'Droid Serif',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'duru-sans' => array(
      'fontname' => 'Duru Sans',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'dynalight' => array(
      'fontname' => 'Dynalight',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'eb-garamond' => array(
      'fontname' => 'EB Garamond',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'eater' => array(
      'fontname' => 'Eater',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'eater-caps' => array(
      'fontname' => 'Eater Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'economica' => array(
      'fontname' => 'Economica',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'electrolize' => array(
      'fontname' => 'Electrolize',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'emblema-one' => array(
      'fontname' => 'Emblema One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'emilys-candy' => array(
      'fontname' => 'Emilys Candy',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'engagement' => array(
      'fontname' => 'Engagement',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'english' => array(
      'fontname' => 'English',
      'variants' => array(
        'n4' => 'Roman',
        'i4' => 'Italic',
      ),
    ),
    'english-small-caps' => array(
      'fontname' => 'English Small Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'enriqueta' => array(
      'fontname' => 'Enriqueta',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'erica-one' => array(
      'fontname' => 'Erica One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'esteban' => array(
      'fontname' => 'Esteban',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'euphoria-script' => array(
      'fontname' => 'Euphoria Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ewert' => array(
      'fontname' => 'Ewert',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'exo' => array(
      'fontname' => 'Exo',
      'variants' => array(
        'n1' => 'Thin',
        'i1' => 'Thin Italic',
        'n2' => 'Extra Light',
        'i2' => 'Extra Light Italic',
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n5' => 'Medium',
        'i5' => 'Medium Italic',
        'n6' => 'Semibold',
        'i6' => 'Semibold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
        'n8' => 'Extra Bold',
        'i8' => 'Extra Bold Italic',
        'n9' => 'Black',
        'i9' => 'Black Italic',
      ),
    ),
    'expletus-sans' => array(
      'fontname' => 'Expletus Sans',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n5' => 'Medium',
        'i5' => 'Medium Italic',
        'n6' => 'Semibold',
        'i6' => 'Semibold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'fanwood-text' => array(
      'fontname' => 'Fanwood Text',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'fascinate' => array(
      'fontname' => 'Fascinate',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'fascinate-inline' => array(
      'fontname' => 'Fascinate Inline',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'federant' => array(
      'fontname' => 'Federant',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'federo' => array(
      'fontname' => 'Federo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'felipa' => array(
      'fontname' => 'Felipa',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'flamenco' => array(
      'fontname' => 'Flamenco',
      'variants' => array(
        'n3' => 'Light',
        'n4' => 'Regular',
      ),
    ),
    'flavors' => array(
      'fontname' => 'Flavors',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'fondamento' => array(
      'fontname' => 'Fondamento',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'fontdiner-swanky' => array(
      'fontname' => 'Fontdiner Swanky',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'forum' => array(
      'fontname' => 'Forum',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'fredericka-the-great' => array(
      'fontname' => 'Fredericka the Great',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'fredoka-one' => array(
      'fontname' => 'Fredoka One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'french-canon' => array(
      'fontname' => 'French Canon',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'french-canon-small-caps' => array(
      'fontname' => 'French Canon Small Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'fresca' => array(
      'fontname' => 'Fresca',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'frijole' => array(
      'fontname' => 'Frijole',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'fugaz-one' => array(
      'fontname' => 'Fugaz One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'fusaka-std' => array(
      'fontname' => 'Fusaka Std',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gfs-didot' => array(
      'fontname' => 'GFS Didot',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gfs-neohellenic' => array(
      'fontname' => 'GFS Neohellenic',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'galdeano' => array(
      'fontname' => 'Galdeano',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gentium-basic' => array(
      'fontname' => 'Gentium Basic',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'gentium-book-basic' => array(
      'fontname' => 'Gentium Book Basic',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'geo' => array(
      'fontname' => 'Geo',
      'variants' => array(
        'i4' => 'Oblique',
        'n4' => 'Regular',
      ),
    ),
    'geostar' => array(
      'fontname' => 'Geostar',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'geostar-fill' => array(
      'fontname' => 'Geostar Fill',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'germania-one' => array(
      'fontname' => 'Germania One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'giddyup-std' => array(
      'fontname' => 'Giddyup Std',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'give-you-glory' => array(
      'fontname' => 'Give You Glory',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'glass-antiqua' => array(
      'fontname' => 'Glass Antiqua',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'glegoo' => array(
      'fontname' => 'Glegoo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gloria-hallelujah' => array(
      'fontname' => 'Gloria Hallelujah',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'goblin-one' => array(
      'fontname' => 'Goblin One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gochi-hand' => array(
      'fontname' => 'Gochi Hand',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gorditas' => array(
      'fontname' => 'Gorditas',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'goudy-bookletter-1911' => array(
      'fontname' => 'Goudy Bookletter 1911',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'graduate' => array(
      'fontname' => 'Graduate',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gravitas-one' => array(
      'fontname' => 'Gravitas One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'great-primer' => array(
      'fontname' => 'Great Primer',
      'variants' => array(
        'n4' => 'Roman',
        'i4' => 'Italic',
      ),
    ),
    'great-primer-small-caps' => array(
      'fontname' => 'Great Primer Small Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gruppo' => array(
      'fontname' => 'Gruppo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'gudea' => array(
      'fontname' => 'Gudea',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'habibi' => array(
      'fontname' => 'Habibi',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'hammersmith-one' => array(
      'fontname' => 'Hammersmith One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'handlee' => array(
      'fontname' => 'Handlee',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'happy-monkey' => array(
      'fontname' => 'Happy Monkey',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'henny-penny' => array(
      'fontname' => 'Henny Penny',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'herr-von-muellerhoff' => array(
      'fontname' => 'Herr Von Muellerhoff',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'hobo-std' => array(
      'fontname' => 'Hobo Std',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'holtwood-one-sc' => array(
      'fontname' => 'Holtwood One SC',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'homemade-apple' => array(
      'fontname' => 'Homemade Apple',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'homenaje' => array(
      'fontname' => 'Homenaje',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'iceberg' => array(
      'fontname' => 'Iceberg',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'iceland' => array(
      'fontname' => 'Iceland',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'immi-five-of-five' => array(
      'fontname' => 'Immi Five Of Five',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'imprima' => array(
      'fontname' => 'Imprima',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'inconsolata' => array(
      'fontname' => 'Inconsolata',
      'variants' => array(
        'n5' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'inder' => array(
      'fontname' => 'Inder',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'indie-flower' => array(
      'fontname' => 'Indie Flower',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'inika' => array(
      'fontname' => 'Inika',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'irish-grover' => array(
      'fontname' => 'Irish Grover',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'irish-growler' => array(
      'fontname' => 'Irish Growler',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'istok-web' => array(
      'fontname' => 'Istok Web',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'italiana' => array(
      'fontname' => 'Italiana',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'italianno' => array(
      'fontname' => 'Italianno',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'jim-nightshade' => array(
      'fontname' => 'Jim Nightshade',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'jockey-one' => array(
      'fontname' => 'Jockey One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'jolly-lodger' => array(
      'fontname' => 'Jolly Lodger',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'josefin-sans' => array(
      'fontname' => 'Josefin Sans',
      'variants' => array(
        'n1' => 'Thin',
        'i1' => 'Thin Italic',
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n6' => 'Semibold',
        'i6' => 'Semibold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'josefin-slab' => array(
      'fontname' => 'Josefin Slab',
      'variants' => array(
        'n1' => 'Thin',
        'i1' => 'Thin Italic',
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n6' => 'Semibold',
        'i6' => 'Semibold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'judson' => array(
      'fontname' => 'Judson',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'julee' => array(
      'fontname' => 'Julee',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'junge' => array(
      'fontname' => 'Junge',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'jura' => array(
      'fontname' => 'Jura',
      'variants' => array(
        'n3' => 'Light',
        'n4' => 'Regular',
        'n5' => 'Medium',
        'n6' => 'Demibold',
      ),
    ),
    'just-another-hand' => array(
      'fontname' => 'Just Another Hand',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'just-me-again-down-here' => array(
      'fontname' => 'Just Me Again Down Here',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'kaffeesatz' => array(
      'fontname' => 'Kaffeesatz',
      'variants' => array(
        'n1' => 'Extra Light',
        'n3' => 'Light',
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'kameron' => array(
      'fontname' => 'Kameron',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'karla' => array(
      'fontname' => 'Karla',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'kaushan-script' => array(
      'fontname' => 'Kaushan Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'kelly-slab' => array(
      'fontname' => 'Kelly Slab',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'kenia' => array(
      'fontname' => 'Kenia',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'knewave' => array(
      'fontname' => 'Knewave',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'kotta-one' => array(
      'fontname' => 'Kotta One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'kranky' => array(
      'fontname' => 'Kranky',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'kreon' => array(
      'fontname' => 'Kreon',
      'variants' => array(
        'n3' => 'Light',
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'kristi' => array(
      'fontname' => 'Kristi',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'krona-one' => array(
      'fontname' => 'Krona One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'la-belle-aurore' => array(
      'fontname' => 'La Belle Aurore',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lancelot' => array(
      'fontname' => 'Lancelot',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lateef' => array(
      'fontname' => 'Lateef',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lato' => array(
      'fontname' => 'Lato',
      'variants' => array(
        'n1' => 'Hairline',
        'i1' => 'Hairline Italic',
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
        'n9' => 'Black',
        'i9' => 'Black Italic',
      ),
    ),
    'league-gothic' => array(
      'fontname' => 'League Gothic',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'leckerli-one' => array(
      'fontname' => 'Leckerli One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ledger' => array(
      'fontname' => 'Ledger',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lekton' => array(
      'fontname' => 'Lekton',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'lemon' => array(
      'fontname' => 'Lemon',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lilita-one' => array(
      'fontname' => 'Lilita One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'linden-hill' => array(
      'fontname' => 'Linden Hill',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'lobster' => array(
      'fontname' => 'Lobster',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lobster-two' => array(
      'fontname' => 'Lobster Two',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'londrina-outline' => array(
      'fontname' => 'Londrina Outline',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'londrina-shadow' => array(
      'fontname' => 'Londrina Shadow',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'londrina-sketch' => array(
      'fontname' => 'Londrina Sketch',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'londrina-solid' => array(
      'fontname' => 'Londrina Solid',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lora' => array(
      'fontname' => 'Lora',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'love-ya-like-a-sister' => array(
      'fontname' => 'Love Ya Like A Sister',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'loved-by-the-king' => array(
      'fontname' => 'Loved by the King',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'luckiest-guy' => array(
      'fontname' => 'Luckiest Guy',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'lusitana' => array(
      'fontname' => 'Lusitana',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'lustria' => array(
      'fontname' => 'Lustria',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'm-1c' => array(
      'fontname' => 'M+ 1c',
      'variants' => array(
        'n2' => 'Thin',
        'n3' => 'Light',
        'n4' => 'Regular',
        'n5' => 'Medium',
        'n7' => 'Bold ',
        'n8' => 'Black ',
        'n9' => 'Heavy ',
      ),
    ),
    'm-1m' => array(
      'fontname' => 'M+ 1m ',
      'variants' => array(
        'n1' => 'Thin',
        'n2' => 'Light',
        'n4' => 'Regular',
        'n5' => 'Medium',
        'n7' => 'Bold ',
      ),
    ),
    'macondo' => array(
      'fontname' => 'Macondo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'macondo-swash-caps' => array(
      'fontname' => 'Macondo Swash Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'maiden-orange' => array(
      'fontname' => 'Maiden Orange',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'mako' => array(
      'fontname' => 'Mako',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'marck-script' => array(
      'fontname' => 'Marck Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'marko-one' => array(
      'fontname' => 'Marko One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'marmelad' => array(
      'fontname' => 'Marmelad',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'marvel' => array(
      'fontname' => 'Marvel',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'mate' => array(
      'fontname' => 'Mate',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'mate-sc' => array(
      'fontname' => 'Mate SC',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'maven-pro' => array(
      'fontname' => 'Maven Pro',
      'variants' => array(
        'n4' => 'Regular',
        'n5' => 'Medium',
        'n7' => 'Bold',
        'n9' => 'Black',
      ),
    ),
    'meddon' => array(
      'fontname' => 'Meddon',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'medievalsharp' => array(
      'fontname' => 'MedievalSharp',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'medula-one' => array(
      'fontname' => 'Medula One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'megrim' => array(
      'fontname' => 'Megrim',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'merienda-one' => array(
      'fontname' => 'Merienda One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'merriweather' => array(
      'fontname' => 'Merriweather',
      'variants' => array(
        'n3' => 'Light',
        'n4' => 'Regular',
        'n7' => 'Bold',
        'n9' => 'Black',
      ),
    ),
    'metamorphous' => array(
      'fontname' => 'Metamorphous',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'miama' => array(
      'fontname' => 'Miama',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'miltonian' => array(
      'fontname' => 'Miltonian',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'miltonian-tattoo' => array(
      'fontname' => 'Miltonian Tattoo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'miniver' => array(
      'fontname' => 'Miniver',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'miss-fajardose' => array(
      'fontname' => 'Miss Fajardose',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'miss-saint-delafield' => array(
      'fontname' => 'Miss Saint Delafield',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'modern-antiqua' => array(
      'fontname' => 'Modern Antiqua',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'molengo' => array(
      'fontname' => 'Molengo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'monofett' => array(
      'fontname' => 'Monofett',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'monoton' => array(
      'fontname' => 'Monoton',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'monsieur-la-doulaise' => array(
      'fontname' => 'Monsieur La Doulaise',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'montaga' => array(
      'fontname' => 'Montaga',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'montez' => array(
      'fontname' => 'Montez',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'montserrat' => array(
      'fontname' => 'Montserrat',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'mountains-of-christmas' => array(
      'fontname' => 'Mountains of Christmas',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'mr-bedfort' => array(
      'fontname' => 'Mr Bedfort',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'mr-dafoe' => array(
      'fontname' => 'Mr Dafoe',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'mr-de-haviland' => array(
      'fontname' => 'Mr De Haviland',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'mrs-saint-delafield' => array(
      'fontname' => 'Mrs Saint Delafield',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'mrs-sheppards' => array(
      'fontname' => 'Mrs Sheppards',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'muli' => array(
      'fontname' => 'Muli',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'mystery-quest' => array(
      'fontname' => 'Mystery Quest',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'neuton' => array(
      'fontname' => 'Neuton',
      'variants' => array(
        'n2' => 'ExtraLight',
        'n3' => 'Light',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'n8' => 'Extra Bold',
      ),
    ),
    'neuton-cursive' => array(
      'fontname' => 'Neuton Cursive',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'niconne' => array(
      'fontname' => 'Niconne',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nixie-one' => array(
      'fontname' => 'Nixie One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nobile' => array(
      'fontname' => 'Nobile',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n5' => 'Medium',
        'i5' => 'Medium Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'norican' => array(
      'fontname' => 'Norican',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nosifer' => array(
      'fontname' => 'Nosifer',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nothing-you-could-do' => array(
      'fontname' => 'Nothing You Could Do',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'noticia-text' => array(
      'fontname' => 'Noticia Text',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'nova-cut' => array(
      'fontname' => 'Nova Cut',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nova-flat' => array(
      'fontname' => 'Nova Flat',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nova-mono' => array(
      'fontname' => 'Nova Mono',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nova-oval' => array(
      'fontname' => 'Nova Oval',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nova-round' => array(
      'fontname' => 'Nova Round',
      'variants' => array(
        'n4' => 'Book',
      ),
    ),
    'nova-script' => array(
      'fontname' => 'Nova Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nova-slim' => array(
      'fontname' => 'Nova Slim',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'nova-square' => array(
      'fontname' => 'Nova Square',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'numans' => array(
      'fontname' => 'Numans',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'old-standard' => array(
      'fontname' => 'Old Standard',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'oldenburg' => array(
      'fontname' => 'Oldenburg',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'open-sans' => array(
      'fontname' => 'Open Sans',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n6' => 'Semi Bold',
        'i6' => 'Semi Bold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
        'n8' => 'Extra Bold',
        'i8' => 'Extra Bold Italic',
      ),
    ),
    'open-sans-condensed' => array(
      'fontname' => 'Open Sans Condensed',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n7' => 'Bold',
      ),
    ),
    'orbitron' => array(
      'fontname' => 'Orbitron',
      'variants' => array(
        'n3' => 'Light',
        'n5' => 'Regular',
        'n7' => 'Bold',
        'n9' => 'Black',
      ),
    ),
    'original-surfer' => array(
      'fontname' => 'Original Surfer',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'over-the-rainbow' => array(
      'fontname' => 'Over the Rainbow',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'overlock' => array(
      'fontname' => 'Overlock',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
        'n9' => 'Black',
        'i9' => 'Black Italic',
      ),
    ),
    'overlock-sc' => array(
      'fontname' => 'Overlock SC',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ovo' => array(
      'fontname' => 'Ovo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'pt-mono' => array(
      'fontname' => 'PT Mono',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'pt-sans' => array(
      'fontname' => 'PT Sans',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'pt-sans-caption' => array(
      'fontname' => 'PT Sans Caption',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'pt-sans-narrow' => array(
      'fontname' => 'PT Sans Narrow',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'pt-serif' => array(
      'fontname' => 'PT Serif',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'pt-serif-caption' => array(
      'fontname' => 'PT Serif Caption',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'pacifico' => array(
      'fontname' => 'Pacifico',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'parisienne' => array(
      'fontname' => 'Parisienne',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'passero-one' => array(
      'fontname' => 'Passero One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'passion-one' => array(
      'fontname' => 'Passion One',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
        'n9' => 'Black',
      ),
    ),
    'patrick-hand' => array(
      'fontname' => 'Patrick Hand',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'patua-one' => array(
      'fontname' => 'Patua One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'paytone-one' => array(
      'fontname' => 'Paytone One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'permanent-marker' => array(
      'fontname' => 'Permanent Marker',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'petrona' => array(
      'fontname' => 'Petrona',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'philosopher' => array(
      'fontname' => 'Philosopher',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'piedra' => array(
      'fontname' => 'Piedra',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'pinyon-script' => array(
      'fontname' => 'Pinyon Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'plaster' => array(
      'fontname' => 'Plaster',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'play' => array(
      'fontname' => 'Play',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'playball' => array(
      'fontname' => 'Playball',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'playfair-display' => array(
      'fontname' => 'Playfair Display',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'podkova' => array(
      'fontname' => 'Podkova',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'poiret-one' => array(
      'fontname' => 'Poiret One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'poller-one' => array(
      'fontname' => 'Poller One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'poly' => array(
      'fontname' => 'Poly',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'pompiere' => array(
      'fontname' => 'Pompiere',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'pontano-sans' => array(
      'fontname' => 'Pontano Sans',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'port-lligat-sans' => array(
      'fontname' => 'Port Lligat Sans',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'port-lligat-slab' => array(
      'fontname' => 'Port Lligat Slab',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'prata' => array(
      'fontname' => 'Prata',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'princess-sofia' => array(
      'fontname' => 'Princess Sofia',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'prosto-one' => array(
      'fontname' => 'Prosto One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'puritan' => array(
      'fontname' => 'Puritan',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'quantico' => array(
      'fontname' => 'Quantico',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'quattrocento' => array(
      'fontname' => 'Quattrocento',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'quattrocento-sans' => array(
      'fontname' => 'Quattrocento Sans',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'questrial' => array(
      'fontname' => 'Questrial',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'quicksand' => array(
      'fontname' => 'Quicksand',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'qwigley' => array(
      'fontname' => 'Qwigley',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'radley' => array(
      'fontname' => 'Radley',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'raleway' => array(
      'fontname' => 'Raleway',
      'variants' => array(
        'n1' => 'Thin',
      ),
    ),
    'rammetto-one' => array(
      'fontname' => 'Rammetto One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'rancho' => array(
      'fontname' => 'Rancho',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'rationale' => array(
      'fontname' => 'Rationale',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'redressed' => array(
      'fontname' => 'Redressed',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'reenie-beanie' => array(
      'fontname' => 'Reenie Beanie',
      'variants' => array(
        'n5' => 'Regular',
      ),
    ),
    'revalia' => array(
      'fontname' => 'Revalia',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ribeye' => array(
      'fontname' => 'Ribeye',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ribeye-marrow' => array(
      'fontname' => 'Ribeye Marrow',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'righteous' => array(
      'fontname' => 'Righteous',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'rochester' => array(
      'fontname' => 'Rochester',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'rock-salt' => array(
      'fontname' => 'Rock Salt',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ropa-sans' => array(
      'fontname' => 'Ropa Sans',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'rosario' => array(
      'fontname' => 'Rosario',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'rouge-script' => array(
      'fontname' => 'Rouge Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ruda' => array(
      'fontname' => 'Ruda',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
        'n9' => 'Black',
      ),
    ),
    'ruge-boogie' => array(
      'fontname' => 'Ruge Boogie',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ruluko' => array(
      'fontname' => 'Ruluko',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ruslan-display' => array(
      'fontname' => 'Ruslan Display',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ruthie' => array(
      'fontname' => 'Ruthie',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sail' => array(
      'fontname' => 'Sail',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'salsa' => array(
      'fontname' => 'Salsa',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sancreek' => array(
      'fontname' => 'Sancreek',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sansita-one' => array(
      'fontname' => 'Sansita One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sanvito-pro-display' => array(
      'fontname' => 'Sanvito Pro Display',
      'variants' => array(
        'n7' => 'Bold',
      ),
    ),
    'sarina' => array(
      'fontname' => 'Sarina',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'satisfy' => array(
      'fontname' => 'Satisfy',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'schoolbell' => array(
      'fontname' => 'Schoolbell',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'seaweed-script' => array(
      'fontname' => 'Seaweed Script',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sevillana' => array(
      'fontname' => 'Sevillana',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'shadows-into-light' => array(
      'fontname' => 'Shadows Into Light',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'shadows-into-light-two' => array(
      'fontname' => 'Shadows Into Light Two',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'shanti' => array(
      'fontname' => 'Shanti',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'share-regular' => array(
      'fontname' => 'Share Regular',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'shojumaru' => array(
      'fontname' => 'Shojumaru',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'short-stack' => array(
      'fontname' => 'Short Stack',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'shuriken-std' => array(
      'fontname' => 'Shuriken Std',
      'variants' => array(
        'n4' => 'Boy',
      ),
    ),
    'sigmar-one' => array(
      'fontname' => 'Sigmar One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'simonetta' => array(
      'fontname' => 'Simonetta',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
      ),
    ),
    'sirin-stencil' => array(
      'fontname' => 'Sirin Stencil',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'six-caps' => array(
      'fontname' => 'Six Caps',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'slackey' => array(
      'fontname' => 'Slackey',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'smokum' => array(
      'fontname' => 'Smokum',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'smythe' => array(
      'fontname' => 'Smythe',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sniglet' => array(
      'fontname' => 'Sniglet',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'snippet' => array(
      'fontname' => 'Snippet',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sofia' => array(
      'fontname' => 'Sofia',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sonsie-one' => array(
      'fontname' => 'Sonsie One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sorts-mill-goudy' => array(
      'fontname' => 'Sorts Mill Goudy',
      'variants' => array(
        'n5' => 'Regular',
        'i5' => 'Italic',
      ),
    ),
    'source-code-pro' => array(
      'fontname' => 'Source Code Pro',
      'variants' => array(
        'n2' => 'Extra Light',
        'n3' => 'Light',
        'n4' => 'Regular',
        'n6' => 'Semibold',
        'n7' => 'Bold',
        'n9' => 'Black',
      ),
    ),
    'source-sans-pro' => array(
      'fontname' => 'Source Sans Pro',
      'variants' => array(
        'n2' => 'Extra Light',
        'i2' => 'Extra Light Italic',
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n6' => 'Semibold',
        'i6' => 'Semibold Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
        'n9' => 'Black',
        'i9' => 'Black Italic',
      ),
    ),
    'special-elite' => array(
      'fontname' => 'Special Elite',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'spicy-rice' => array(
      'fontname' => 'Spicy Rice',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'spinnaker' => array(
      'fontname' => 'Spinnaker',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'spirax' => array(
      'fontname' => 'Spirax',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'squada-one' => array(
      'fontname' => 'Squada One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'stardos-stencil' => array(
      'fontname' => 'Stardos Stencil',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'stencil-std' => array(
      'fontname' => 'Stencil Std',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'stint-ultra-condensed' => array(
      'fontname' => 'Stint Ultra Condensed',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'stint-ultra-expanded' => array(
      'fontname' => 'Stint Ultra Expanded',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'stoke' => array(
      'fontname' => 'Stoke',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'strong' => array(
      'fontname' => 'Strong',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'strumpf-std' => array(
      'fontname' => 'Strumpf Std',
      'variants' => array(
        'n7' => 'Contour',
      ),
    ),
    'sue-ellen-francisco' => array(
      'fontname' => 'Sue Ellen Francisco',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'sunshiney' => array(
      'fontname' => 'Sunshiney',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'supermercado-one' => array(
      'fontname' => 'Supermercado One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'swanky-and-moo-moo' => array(
      'fontname' => 'Swanky and Moo Moo',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'syncopate' => array(
      'fontname' => 'Syncopate',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'tangerine' => array(
      'fontname' => 'Tangerine',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'telex' => array(
      'fontname' => 'Telex',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'tenor-sans' => array(
      'fontname' => 'Tenor Sans',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'the-girl-next-door' => array(
      'fontname' => 'The Girl Next Door',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'tienne' => array(
      'fontname' => 'Tienne',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
        'n9' => 'Heavy',
      ),
    ),
    'tinos' => array(
      'fontname' => 'Tinos',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'titan-one' => array(
      'fontname' => 'Titan One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'trade-winds' => array(
      'fontname' => 'Trade Winds',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'trochut' => array(
      'fontname' => 'Trochut',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
      ),
    ),
    'trykker' => array(
      'fontname' => 'Trykker',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'tulpen-one' => array(
      'fontname' => 'Tulpen One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ubuntu' => array(
      'fontname' => 'Ubuntu',
      'variants' => array(
        'n3' => 'Light',
        'i3' => 'Light Italic',
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n5' => 'Medium',
        'i5' => 'Medium Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'ubuntu-condensed' => array(
      'fontname' => 'Ubuntu Condensed',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'ubuntu-mono' => array(
      'fontname' => 'Ubuntu Mono',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Regular Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'ultra' => array(
      'fontname' => 'Ultra',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'uncial-antiqua' => array(
      'fontname' => 'Uncial Antiqua',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'unifrakturcook' => array(
      'fontname' => 'UnifrakturCook',
      'variants' => array(
        'n7' => 'Bold',
      ),
    ),
    'unifrakturmaguntia' => array(
      'fontname' => 'UnifrakturMaguntia',
      'variants' => array(
        'n4' => 'Book',
      ),
    ),
    'unkempt' => array(
      'fontname' => 'Unkempt',
      'variants' => array(
        'n4' => 'Regular',
        'n7' => 'Bold',
      ),
    ),
    'unlock' => array(
      'fontname' => 'Unlock',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'unna' => array(
      'fontname' => 'Unna',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'vt323' => array(
      'fontname' => 'VT323',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'varela' => array(
      'fontname' => 'Varela',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'varela-round' => array(
      'fontname' => 'Varela Round',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'vast-shadow' => array(
      'fontname' => 'Vast Shadow',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'vera-sans' => array(
      'fontname' => 'Vera Sans',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'vibur' => array(
      'fontname' => 'Vibur',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'vidaloka' => array(
      'fontname' => 'Vidaloka',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'viga' => array(
      'fontname' => 'Viga',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'voces' => array(
      'fontname' => 'Voces',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'volkhov' => array(
      'fontname' => 'Volkhov',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'vollkorn' => array(
      'fontname' => 'Vollkorn',
      'variants' => array(
        'n4' => 'Regular',
        'i4' => 'Italic',
        'n7' => 'Bold',
        'i7' => 'Bold Italic',
      ),
    ),
    'voltaire' => array(
      'fontname' => 'Voltaire',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'waiting-for-the-sunrise' => array(
      'fontname' => 'Waiting for the Sunrise',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'wallpoet' => array(
      'fontname' => 'Wallpoet',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'walter-turncoat' => array(
      'fontname' => 'Walter Turncoat',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'wellfleet' => array(
      'fontname' => 'Wellfleet',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'wire-one' => array(
      'fontname' => 'Wire One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'yellowtail' => array(
      'fontname' => 'Yellowtail',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'yeseva-one' => array(
      'fontname' => 'Yeseva One',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'yesteryear' => array(
      'fontname' => 'Yesteryear',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
    'zeyada' => array(
      'fontname' => 'Zeyada',
      'variants' => array(
        'n4' => 'Regular',
      ),
    ),
  );
}
